# -*- coding: utf-8 -*-
"""trab0_pdi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WqKks70qtAkL7R36qkJ5jzR4G4vHlSwl
"""

#!wget http://www.ic.unicamp.br/~helio/imagens_png/baboon.png
#!apt-get -qq install -y libsm6 libxext6 && pip install -q -U opencv-python

import numpy as np
import cv2
from matplotlib import pyplot as plt

"""1.1 Histograma de imagens"""

im = cv2.imread('baboon.png',cv2.IMREAD_GRAYSCALE)

plt.figure(1)
plt.imshow(im,cmap='gray')

plt.figure(2)
plt.hist(im.ravel(),256,[0,256])
plt.xlabel('Niveis de cinza')
plt.ylabel('Frequencia')
plt.savefig('hist.png')

"""1.2 Estatísticas de imagem"""

print('largura: %d'%im.shape[1])
print('altura: %d'%im.shape[0])
print('intensidade mínima: %d'%np.min(im))
print('intensidade máxima: %d'%np.max(im))
print('intensidade média: %.2f'%np.mean(im))

"""1.3 Transformação de intensidade

*   Negativo da imagem
"""

neg = cv2.bitwise_not(im)
plt.figure(3)
plt.imshow(neg,cmap='gray')
plt.savefig('neg.png')
"""*   Converter intensidades para o intervalo [120,180]"""

# ajeitar
im_ = np.zeros(im.shape,dtype=int)
for r in range(im_.shape[0]):
  for c in range(im_.shape[1]):
    im_[r][c] = int(60*im[r][c]/255.0) + 120

plt.figure(4)
plt.imshow(im_,cmap='gray',vmin=120,vmax=180)
plt.figure(5)
plt.imshow(im,cmap='gray')

plt.show()

